### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by c2c2** [joomla/Joomla-3.2-Hello-World-Component#12] opened 2014-12-12 12:33 UTC
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '﻿' at line 1 SQL=﻿
when create new package from changed file and try to install that error showed and install can't complete

**Comment by betweenbrain** [comment] 2014-12-12 13:06
We would need more specifics about what file/branch that you are referring to.

**Comment by c2c2** [comment] 2014-12-15 19:13
Hi, i found it
Important Note: When saving the SQL files in utf8, be sure to save them as utf8 NOT BOM or the query will fail with MySQL error #1064.
but i don know how create a utf8 NOT BOM sql file?

**Comment by betweenbrain** [comment] 2014-12-15 19:44
Hello,

Yes, that may be the cause of the issue. Creating a file without BOM depends on the program that you use to create it. There is a topic on the Joomla forum that may help - http://forum.joomla.org/viewtopic.php?t=213283

**Comment by Hutchy68** [comment] 2015-02-20 23:24
closing as solved

**Closed as completed by Hutchy68** 2015-02-20 23:24 UTC
